### ISSUE TITLE
Opaque directories not merged correctly during image squash

### ISSUE THREAD

**Issue by luhring** [anchore/stereoscope#48]
Stereoscope is mishandling situations where opaque directories in upper layers are merged down into lower layers, particularly when the directory doesn't exist in the lower layer.

There are two noteworthy problems here:

1. The opaque directory is not added to the lower layer at the end of the merge (and it should be).
1. Because of the above problem, opaque directories are added _implicitly_ during the merge in such a way that prevents these directories from being correctly added to the image's `FileCatalog`, on which consumers depend. Consumers that try to access such directories in a squashed image receive the error "could not find file". This implicit addition of directories during merge operations should be removed.

Tasks:

- [x] add tests for this case
- [x] add the directory from the upper tree even when it contains `.wh..wh..opq` during merge
- [x] don't allow for implicit addition of parents during `AddPath` during merge
- [x] validate that when we create a tree, all its entries are found in the FileCatalog
